In [1]:
nums = range(5)
print nums

[0, 1, 2, 3, 4]


In [4]:
nums[1:] = [10,11]
print nums

[0, 10, 11]


In [5]:
animals = ['cat','dog','horse']
for idx,animal in enumerate(animals):#enumerate func is used for getting the index
    print "#%d. %s"%(idx+1,animal)

#1. cat
#2. dog
#3. horse


In [6]:
#List comprehension
nums = range(5)
cubes = [x**3 for x in nums]#form a list with each value of x
print cubes

[0, 1, 8, 27, 64]


In [7]:
#List comprehension with condition
num = range(0,100,3)
cubes = [x**3 for x in num: if x%2==0]
print cubes

SyntaxError: invalid syntax (<ipython-input-7-60599b631cfe>, line 3)

In [8]:
num = range(0,100,3)
cubes = [x**3 for x in num if x%2==0]
print cubes

[0, 216, 1728, 5832, 13824, 27000, 46656, 74088, 110592, 157464, 216000, 287496, 373248, 474552, 592704, 729000, 884736]


In [9]:
d = {'cat':'mew', 'dog':'bhow bhow', 'goat':'mah mah'}
print d

{'goat': 'mah mah', 'dog': 'bhow bhow', 'cat': 'mew'}


In [10]:
print 'goat' in d#check if element exists

True


In [11]:
d['Subhankar'] = 'Yippee'
d

{'Subhankar': 'Yippee', 'cat': 'mew', 'dog': 'bhow bhow', 'goat': 'mah mah'}

In [12]:
print d.get('Hippo','NA')

NA


In [14]:
print d.get('Subhankar','NA')

Yippee


In [16]:
del d['goat']
d

{'Subhankar': 'Yippee', 'cat': 'mew', 'dog': 'bhow bhow'}

In [17]:
print d.get('goat','NA')

NA


In [18]:
d

{'Subhankar': 'Yippee', 'cat': 'mew', 'dog': 'bhow bhow'}

In [20]:
#Iterate over the keys in the dictionary
for x,y in d.iteritems():
    print "%s says %s"%(x,y)

dog says bhow bhow
Subhankar says Yippee
cat says mew


In [21]:
nums = range(0,100,3)
print nums

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


In [22]:
#Build a dict of cubes which are divisible by 6
num2cubes = {x:x**3 for x in nums if x**3 %6 == 0}
print num2cubes

{0: 0, 96: 884736, 66: 287496, 36: 46656, 6: 216, 72: 373248, 42: 74088, 12: 1728, 78: 474552, 48: 110592, 18: 5832, 84: 592704, 54: 157464, 24: 13824, 90: 729000, 60: 216000, 30: 27000}


In [23]:
d

{'Subhankar': 'Yippee', 'cat': 'mew', 'dog': 'bhow bhow'}

In [24]:
types = d.keys()
types

['dog', 'Subhankar', 'cat']

In [25]:
types = set(types)#List2Set
types

{'Subhankar', 'cat', 'dog'}

In [26]:
print 'cat' in types

True


In [27]:
types.add('goat')
types

{'Subhankar', 'cat', 'dog', 'goat'}

In [28]:
types.remove('dog')
types

{'Subhankar', 'cat', 'goat'}

In [30]:
#Iterate over the set
for idx,type in enumerate(types):
    print "#%d.%s"%(idx+1,type)#set has no order of storing the items. so it prints randomly

#1.goat
#2.Subhankar
#3.cat


In [33]:
from math import floor,sqrt
nums = range(0,50,7)
floors = {floor(sqrt(x)) for x in nums if x%6!=0}
print floors

set([2.0, 3.0, 4.0, 5.0, 7.0])


In [34]:
d = {(x, x + 1): x for x in range(10)}
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [35]:
t = (2,3)
print t in d.keys()

True


In [36]:
d[t]

2

In [3]:
def hey(name, case=False):
    if case:
        print "HELLO %s"%(name.upper())
    else:
        print "Hello %s"%(name)
hey("Subhankar")
hey("Sourav", True)

Hello Subhankar
HELLO SOURAV


In [1]:
class Greet(object):
    def __init__(self, name):
        self.name=name
    def hey(self, case=False):
        if case:
            print "HELLO %s"%(self.name.upper())
        else:
            print "Hello %s"%(self.name)
obj = Greet("Subhankar")
obj.hey()
obj2 = Greet("Sourav")
obj2.hey(True)

Hello Subhankar
HELLO SOURAV


In [6]:
import numpy as np
a = np.array(range(10))
print type(a), a
print a.shape
print a[2]
a[2]= 34
print a

<type 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]
(10,)
2
[ 0  1 34  3  4  5  6  7  8  9]


In [9]:
b = np.array([range(5), range(10)])
print b[0][3], b[1][8]# same as [0,3] & [1,8]
print b.shape
c = np.array([range(0,20,3), range(20,40,3)])
print c, c.shape

3 8
(2,)
[[ 0  3  6  9 12 15 18]
 [20 23 26 29 32 35 38]] (2, 7)


In [13]:
d = np.zeros((5,5))
print d

e = np.ones((4,4))
print e

f = np.full((5,5),8)
print f

g = np.full((10),4)
print g

h = np.eye(4)
print h

i = np.random.random((3,3))
print i

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 8.  8.  8.  8.  8.]
 [ 8.  8.  8.  8.  8.]
 [ 8.  8.  8.  8.  8.]
 [ 8.  8.  8.  8.  8.]
 [ 8.  8.  8.  8.  8.]]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.35933517  0.50348109  0.18362744]
 [ 0.85947691  0.73092944  0.73935281]
 [ 0.64236832  0.75558051  0.16715916]]


In [14]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
suba = a[:2,1:3]
suba

array([[2, 3],
       [6, 7]])

In [16]:
suba = np.array([[12, 13], [16, 17]])
print a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
suba = a[:2,1:3]
suba[0,1] = 99
suba[1,0] = 153
print a

[[  1   2  99   4]
 [  5 153   7   8]
 [  9  10  11  12]]


In [24]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
rr1 = a[1,:]
rr2 = a[1:2,:]
print rr1, rr2
print rr1.shape, rr2.shape# Rank 1 & Rank 2 views respectively

[5 6 7 8] [[5 6 7 8]]
(4,) (1, 4)


In [25]:
cr1 = a[:,1]
cr2 = a[:,1:2]
print cr1, cr2, cr1.shape, cr2.shape

[ 2  6 10] [[ 2]
 [ 6]
 [10]] (3,) (3, 1)


In [2]:
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])
print a[[0, 1, 2], [0, 1, 0]]

[1 4 5]


In [3]:
print a[[0,1,2],[1,0,1]]#[2,3,6] converts to[0,1][1,0][2,1]
print a[[1,2],[0,0]]#[3,5]

[2 3 6]
[3 5]


In [4]:
print np.array([a[0,1],a[1,0],a[2,1]])

[2 3 6]


In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([2,1,2,0])
print a[np.arange(4), b]#http://sage.math.canterbury.ac.nz/home/pub/72/cells/132/docs-0.html

[ 3  5  9 10]


In [10]:
a[np.arange(4), b] += 50
print a

[[ 1  2 53]
 [ 4 55  6]
 [ 7  8 59]
 [60 11 12]]


In [23]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
boolidx = ( a==2)
print boolidx

[[False  True False]
 [False False False]
 [False False False]
 [False False False]]


In [24]:
boolidx = (a > 2)
print boolidx

[[False False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [25]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print bool_idx

[[False False]
 [ True  True]
 [ True  True]]


In [26]:
boolidx = (a > 4)
print boolidx

[[False False]
 [False False]
 [ True  True]]


In [28]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
boolidx = (a>2)
print a[boolidx]
print a[a>2]

[ 3  4  5  6  6  7  8  9 10 11]
[ 3  4  5  6  6  7  8  9 10 11]


In [31]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
b = np.array([[11,12,13],[14,15,16],[16,17,18],[19,110,111]])
print np.add(a,b)
print np.subtract(a,b)
print np.multiply(a,b)
print np.divide(a,b)

[[ 12  14  16]
 [ 18  20  22]
 [ 22  24  26]
 [ 28 120 122]]
[[ -10  -10  -10]
 [ -10  -10  -10]
 [ -10  -10  -10]
 [ -10 -100 -100]]
[[  11   24   39]
 [  56   75   96]
 [  96  119  144]
 [ 171 1100 1221]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [32]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]], dtype=np.float64)
b = np.array([[11,12,13],[14,15,16],[16,17,18],[19,110,111]], dtype=np.float64)
print np.divide(a,b)

[[ 0.09090909  0.16666667  0.23076923]
 [ 0.28571429  0.33333333  0.375     ]
 [ 0.375       0.41176471  0.44444444]
 [ 0.47368421  0.09090909  0.0990991 ]]


In [33]:
print np.sqrt(b)

[[  3.31662479   3.46410162   3.60555128]
 [  3.74165739   3.87298335   4.        ]
 [  4.           4.12310563   4.24264069]
 [  4.35889894  10.48808848  10.53565375]]


In [35]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
b = np.array([[11,12,13],[14,15,16],[16,17,18]])
print np.dot(a,b)

[[ 87  93  99]
 [210 225 240]
 [292 313 334]
 [415 445 475]]


In [36]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
print np.dot(x,v)
print np.dot(v,x)

[29 67]
[39 58]


In [37]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
b = np.array([[11,12,13],[14,15,16],[16,17,18]])
print np.sum(a)

72


In [39]:
print np.sum(a,axis=0)#Compute sum of each column
print np.sum(b,axis=1)#Compute sum of each row

[20 24 28]
[36 45 51]


In [40]:
print a
print a.T#Transpose

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
[[ 1  4  6  9]
 [ 2  5  7 10]
 [ 3  6  8 11]]


In [5]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([10,100,1000])
v = np.empty_like(x)
for i in range(3):
    v[i,:] = x[i,:] + y
print v

[[  11  102 1003]
 [  14  105 1006]
 [  17  108 1009]
 [  10   11   12]]


In [7]:
yy = np.tile(y, (3,2,1))#Order:No. of grids, No. of rows, No. of Columns
print yy

[[[  10  100 1000]
  [  10  100 1000]]

 [[  10  100 1000]
  [  10  100 1000]]

 [[  10  100 1000]
  [  10  100 1000]]]


In [8]:
zz = np.tile(y,(1,2,3))
print zz

[[[  10  100 1000   10  100 1000   10  100 1000]
  [  10  100 1000   10  100 1000   10  100 1000]]]


In [12]:
yyy = np.tile(y,(4,1))
xx = x + yyy
print xx
print yyy

[[  11  102 1003]
 [  14  105 1006]
 [  17  108 1009]
 [  20  111 1012]]
[[  10  100 1000]
 [  10  100 1000]
 [  10  100 1000]
 [  10  100 1000]]


In [13]:
xxx = x + y
print xxx

[[  11  102 1003]
 [  14  105 1006]
 [  17  108 1009]
 [  20  111 1012]]


In [14]:
yyyy = np.tile(y,(1,4))
print yyyy

[[  10  100 1000   10  100 1000   10  100 1000   10  100 1000]]


In [16]:
v = np.array([1,2,3])
w = np.array([4,5])
vv = np.reshape(v,(3,1))
print v
print vv

[1 2 3]
[[1]
 [2]
 [3]]


In [17]:
print vv * w

[[ 4  5]
 [ 8 10]
 [12 15]]


In [21]:
print x
w = [4,5,6,7]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
print x + w

[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]
 [14 16 18]]


In [25]:
x.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [30]:
x = np.array([[1,2,3], [4,5,6]])
w = np.array([4,5])
print x
print w

[[1 2 3]
 [4 5 6]]
[4 5]


In [31]:
print (x.T + w).T

[[ 5  6  7]
 [ 9 10 11]]


In [33]:
xx = np.array([range(4),range(4),range(4),range(4),range(4)])
print xx

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [34]:
ww = np.array(range(5))
print ww

[0 1 2 3 4]


In [36]:
print xx.T + ww

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [37]:
print (xx.T + ww).T

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
